function pop_validatebids()
        com = [ 'bidsFolderxx = uigetdir(''Pick a BIDS output folder'');' ...
            'if ~isequal(bidsFolderxx, 0), set(findobj(gcbf, ''tag'', ''outputfolder''), ''string'', bidsFolderxx); end;' ...
            'clear bidsFolderxx;' ];
        uilist = { ...
        { 'Style', 'text', 'string', 'Validate BIDS dataset', 'fontweight', 'bold'  }, ...
        {} ...
        { 'Style', 'text', 'string', 'BIDS folder:' }, ...
        { 'Style', 'edit', 'string',   fullfile('.', 'BIDS_EXPORT') 'tag' 'outputfolder' }, ...
        { 'Style', 'pushbutton', 'string', '...' 'callback' com }, ...
        { 'Style', 'text', 'string', '' }, ...
        { 'Style', 'pushbutton', 'string', 'Validate' 'tag' 'validateBtn' 'callback' @validateCB }, ...
        { 'Style', 'text', 'string', ''}, ...
        };
    geometry = { [1] [1] [0.2 0.7 0.1] [1 1 1] };
    geomvert =   [1  1 1  1];
    [results,userdata,~,restag] = inputgui( 'geometry', geometry, 'geomvert', geomvert, 'uilist', uilist, 'helpcom', 'pophelp(''pop_validatebids'');', 'title', 'Validate BIDS dataset-- pop_validatebids()');
    
    function validateCB(src, event)
        obj = findobj('Tag','outputfolder');
        dir = obj.String;
        system([fullfile(fileparts(which('pop_exportbids')), 'bids-validator-macos') ' ' dir]); edit eegplugin_bids.m
      
        
    end
end